/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef service_CONSTANTS_H
#define service_CONSTANTS_H

#include "service_types.h"



class serviceConstants {
 public:
  serviceConstants();

};

extern const serviceConstants g_service_constants;



#endif
