/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "service_constants.h"



const serviceConstants g_service_constants;

serviceConstants::serviceConstants() {
}



